<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");?>
<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.viewed.products", 
	"mshop", 
	array(
		"COMPONENT_TEMPLATE" => "main",
		"BASKET_ATCTION" => $_POST["basketaction"],
		"IBLOCK_TYPE" => "new_cat",
		"IBLOCK_ID" => 26,
		"SHOW_FROM_SECTION" => "N",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"SECTION_ELEMENT_ID" => "",
		"SECTION_ELEMENT_CODE" => "",
		"DEPTH" => "",
		"HIDE_NOT_AVAILABLE" => "L",
		"PRODUCT_SUBSCRIPTION" => "",
		"SHOW_MEASURE" => "Y",
		"SHOW_NAME" => "Y",
		"SHOW_IMAGE" => "Y",
		'MESS_BTN_BUY' => "",
		'MESS_BTN_ADD_TO_BASKET' => "",
		'MESS_BTN_SUBSCRIBE' => "",
		'MESS_BTN_DETAIL' => "",
		'MESS_NOT_AVAILABLE' => "",
		"PAGE_ELEMENT_COUNT" => "20",
		"LINE_ELEMENT_COUNT" => "4",
		"TEMPLATE_THEME" => "blue",
		"DETAIL_URL" => "",
		"CACHE_TYPE" => "Y",
		"CACHE_TIME" => "360000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"PRICE_CODE" => array(
			0 => "BASE",
			1 => "OPT",
			2 => "Интернет Розница",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"BASKET_URL" => "/basket/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"SHOW_PRODUCTS_26" => "Y",
		"PROPERTY_CODE_26" => array(
			0 => "BRAND",
			1 => "k_350",
			2 => "k_330",
			3 => "k_345",
			4 => "k_351",
			5 => "k_331",
			6 => "k_334",
			7 => "k_333",
			8 => "k_326",
			9 => "k_335",
			10 => "k_332",
			11 => "PROP_162",
			12 => "PROP_2065",
			13 => "PROP_2054",
			14 => "PROP_2017",
			15 => "PROP_2055",
			16 => "PROP_2069",
			17 => "PROP_2062",
			18 => "PROP_2061",
			19 => "CML2_LINK",
			20 => "MORE_PHOTO",
			21 => "ON_PHOT",
			22 => "SUM_PROD",
			23 => "",
		),
		"TOP_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"CART_PROPERTIES_26" => array(
			0 => "",
			1 => "",
		),
		"ADDITIONAL_PICT_PROP_26" => "MORE_PHOTO",
		"LABEL_PROP_26" => "-",
		"TITLE_BLOCK" => "Ранее вы смотрели",
		"TITLE_BLOCK_BEST" => "Лучшие предложения",
		"DISPLAY_WISH_BUTTONS" => "Y",
		"DISPLAY_COMPARE" => "N",
		"SHOW_TOP_ELEMENTS" => "Y",
		"TOP_ELEMENT_SORT_FIELD" => "shows",
		"TOP_ELEMENT_SORT_ORDER" => "asc",
		"TOP_ELEMENT_SORT_FIELD2" => "shows",
		"TOP_ELEMENT_SORT_ORDER2" => "asc",
		"ELEMENT_COUNT" => "8",
		"OFFERS_CART_PROPERTIES" => array(
		),
		"TOP_OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "",
		),
		"TOP_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"OFFERS_SORT_FIELD" => "shows",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "shows",
		"OFFERS_SORT_ORDER2" => "asc",
		"TOP_OFFERS_LIMIT" => "10",
		"TOP_SECTION_ID" => $_POST["topsecid"],
		"FILTER_NAME" => "MSHOP_SMART_FILTER",
		'PRODUCT_DISPLAY_MODE' => "",
		'OFFER_ADD_PICT_PROP' => "-",
		'OFFER_TREE_PROPS' => array(
		),

	),
	false, array("HIDE_ICONS"=>"Y")
);?>